<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ResellerSystem.Server.FileStorage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
  </ItemGroup>
</Project>
